### ISSUE TITLE
[BUG] PYMEImage YZ projection... not working?

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#811] opened 2021-01-29 02:52 UTC
**Describe the bug**
Looks like side view projection is getting the wrong indices... maybe transposing?

**To Reproduce**
1. render
![Screen Shot 2021-01-28 at 9 45 29 PM](https://user-images.githubusercontent.com/31105780/106224997-41be5e00-61b2-11eb-8c94-12b882036c59.png)

2. crop
![Screen Shot 2021-01-28 at 9 43 36 PM](https://user-images.githubusercontent.com/31105780/106225104-73372980-61b2-11eb-9611-46cb2a56ed32.png)

3. swap to a side view
![Screen Shot 2021-01-28 at 9 43 54 PM](https://user-images.githubusercontent.com/31105780/106225022-4aaf2f80-61b2-11eb-8bcf-7db9831e943b.png)

4. is this a single slice?

**Expected behavior**
project along X within my XY crop

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: osx 10.15
 - Python version: 3.7.7
 - numpy version: 1.19.2
 - wxpython version [if a UI bug]: 4.0.4

**Comment by David-Baddeley** [comment] 2021-02-02 00:24
As it stands, the xz and yz views do not project (viewer projections are strictly x-y only). This is partly by design to avoid performance issues on large data sets, although the GUI is not clear that this is not being performed. It probably wouldn't hurt to expand the projection logic to xz and yz views, but we'd need to think a bit about how to do so in a high performance way.

**Comment by David-Baddeley** [comment] 2021-04-11 23:53
Mostly fixed with alternative functionality in #972, with removing 'live' projection option in the display settings on the TODO pending a functional colour coded z projection mode.

**Closed as completed** 2021-04-11 23:54 UTC
Labels: bug
