### ISSUE TITLE
[BUG] Displaying 3D density reconstructions crashes VisGUI, linux

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#851] opened 2021-02-12 23:46 UTC
**Describe the bug**

<details> <summary> grotesque amount of stuff, including a traceback </summary> 

```

(base) smeagol@smeagol:~/code/python-microscopy$ PYMEVis '/media/smeagol/d5b5c790-4eba-4212-b990-062bba0b7a3b/data/2019_01_21_atubulinCF568_sec61bAF647/recipe_outputs/mapped/fov8_8kframes_filtered.hdf' 
/home/smeagol/miniconda3/lib/python3.6/_collections_abc.py:702: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.
  return len(self._mapping)
/home/smeagol/miniconda3/lib/python3.6/_collections_abc.py:720: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.
  yield from self._mapping
/home/smeagol/code/python-microscopy/PYME/misc/extraCMaps.py:73: MatplotlibDeprecationWarning: 
The revcmap function was deprecated in Matplotlib 3.2 and will be removed two minor releases later. Use Colormap.reversed() instead.
  cmapdat_r = cm.revcmap(ndat[cmapname])
Trying to load 3rd party recipe module nep_fitting.recipe_modules.nep_fits
Loaded 3rd party recipe module nep_fitting.recipe_modules.nep_fits
Trying to load 3rd party recipe module pyme_rcnn.recipe_modules.rcnn_segment
Loaded 3rd party recipe module pyme_rcnn.recipe_modules.rcnn_segment
Trying to load 3rd party recipe module bleaching_tools.python_microscopy.recipe_modules.masked_statistics
ERROR:PYME.recipes.modules:Error loading plugin: bleaching_tools.python_microscopy.recipe_modules.masked_statistics
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/recipes/modules.py", line 41, in <module>
    m = __import__(mn, fromlist=mn.split('.')[:-1])
ModuleNotFoundError: No module named 'bleaching_tools'
Trying to load 3rd party recipe module pyme_omero.recipe_modules.omero_upload
Loaded 3rd party recipe module pyme_omero.recipe_modules.omero_upload
Trying to load 3rd party recipe module quant_condensate.recipe_modules.cluster_quant
Loaded 3rd party recipe module quant_condensate.recipe_modules.cluster_quant
Trying to load 3rd party recipe module localization_survey.recipe_modules.roi_cropping
Loaded 3rd party recipe module localization_survey.recipe_modules.roi_cropping
Trying to load 3rd party recipe module cb_analysis.python_microscopy.recipe_modules.cb_clustering
Loaded 3rd party recipe module cb_analysis.python_microscopy.recipe_modules.cb_clustering
Trying to load 3rd party recipe module nucleus.python_microscopy.recipe_modules.nucleus_metrics
ERROR:PYME.recipes.modules:Error loading plugin: nucleus.python_microscopy.recipe_modules.nucleus_metrics
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/recipes/modules.py", line 41, in <module>
    m = __import__(mn, fromlist=mn.split('.')[:-1])
ModuleNotFoundError: No module named 'nucleus'
Trying to load 3rd party recipe module autoroi.recipe_modules.retrieval
Loaded 3rd party recipe module autoroi.recipe_modules.retrieval
Trying to load 3rd party recipe module nucleus.python_microscopy.recipe_modules.distance_to_membrane
ERROR:PYME.recipes.modules:Error loading plugin: nucleus.python_microscopy.recipe_modules.distance_to_membrane
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/recipes/modules.py", line 41, in <module>
    m = __import__(mn, fromlist=mn.split('.')[:-1])
ModuleNotFoundError: No module named 'nucleus'
Trying to load 3rd party recipe module nucleus.python_microscopy.recipe_modules.shell_fitting
ERROR:PYME.recipes.modules:Error loading plugin: nucleus.python_microscopy.recipe_modules.shell_fitting
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/recipes/modules.py", line 41, in <module>
    m = __import__(mn, fromlist=mn.split('.')[:-1])
ModuleNotFoundError: No module named 'nucleus'
Trying to load 3rd party recipe module autoroi.recipe_modules.mrcnn_segment
Loaded 3rd party recipe module autoroi.recipe_modules.mrcnn_segment
Trying to load 3rd party recipe module autoroi.recipe_modules.features
Loaded 3rd party recipe module autoroi.recipe_modules.features
Trying to load 3rd party recipe module cell_death_detection.python_microscopy.recipe_modules.cell_death
ERROR:PYME.recipes.modules:Error loading plugin: cell_death_detection.python_microscopy.recipe_modules.cell_death
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/recipes/modules.py", line 41, in <module>
    m = __import__(mn, fromlist=mn.split('.')[:-1])
ModuleNotFoundError: No module named 'cell_death_detection'
Trying to load 3rd party recipe module nucleus.python_microscopy.recipe_modules.astigmatism_tools
ERROR:PYME.recipes.modules:Error loading plugin: nucleus.python_microscopy.recipe_modules.astigmatism_tools
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/recipes/modules.py", line 41, in <module>
    m = __import__(mn, fromlist=mn.split('.')[:-1])
ModuleNotFoundError: No module named 'nucleus'
INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
quaternion module not found, disabling custom clip plane orientations
quaternion module not found, disabling custom clip plane orientations
GLib-GIO-Message: 18:38:23.477: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
New Canvas
DEBUG:PYME.LMVis.visCore:Creating VisGUI menu bar
DEBUG:PYME.LMVis.Extras:Initializing QPobjectSegment plugin
DEBUG:PYME.LMVis.Extras:Initializing animation plugin
DEBUG:PYME.LMVis.Extras:Initializing clusterAnalysis plugin
DEBUG:PYME.LMVis.Extras:Initializing dockedPanel plugin
DEBUG:PYME.LMVis.Extras:Initializing extra_layers plugin
DEBUG:PYME.LMVis.Extras:Initializing fiducial plugin
DEBUG:PYME.LMVis.Extras:Initializing flagZMotionArtifacts plugin
DEBUG:root:Adding menu items for event filters
DEBUG:PYME.LMVis.Extras:Initializing fusionUtils plugin
DEBUG:PYME.LMVis.Extras:Initializing multiColourAnalysis plugin
DEBUG:PYME.LMVis.Extras:Initializing multiviewMapping plugin
DEBUG:root:Adding menu items for multi-view manipulation
DEBUG:PYME.LMVis.Extras:Initializing objectMeasurements plugin
DEBUG:PYME.LMVis.Extras:Initializing particleTracking plugin
DEBUG:PYME.LMVis.Extras:Initializing perFrameVariable plugin
DEBUG:PYME.LMVis.Extras:Initializing photophysics plugin
DEBUG:PYME.LMVis.Extras:Initializing pointSetGeneration plugin
DEBUG:PYME.LMVis.Extras:Initializing pointwiseColoc plugin
DEBUG:PYME.LMVis.Extras:Initializing saved_views plugin
Saved Views are deprecated -  use the ones with animation instead and remove me!
DEBUG:PYME.LMVis.Extras:Initializing scaleBox plugin
DEBUG:PYME.LMVis.Extras:Initializing sequentialSpecies plugin
DEBUG:PYME.LMVis.Extras:Initializing setBGImage plugin
DEBUG:PYME.LMVis.Extras:Initializing shiftmapGenerator plugin
DEBUG:PYME.LMVis.Extras:Initializing showShortcuts plugin
DEBUG:PYME.LMVis.Extras:Initializing snapshot plugin
DEBUG:PYME.LMVis.Extras:Initializing spherical_harmonics plugin
DEBUG:root:Adding menu items for spherical harmonic (shell) fitting
DEBUG:PYME.LMVis.Extras:Initializing subsets plugin
DEBUG:PYME.LMVis.Extras:Initializing surface_fitting plugin
DEBUG:PYME.LMVis.Extras:Initializing temperaturePlot plugin
DEBUG:PYME.LMVis.Extras:Initializing vibration plugin
DEBUG:root:Adding menu items for OMERO loading
ERROR:PYME.LMVis.Extras:Error loading plugin: nucleus.python_microscopy.visgui_modules.shell_fitting
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/Extras/__init__.py", line 46, in InitPlugins
    m = __import__(mn, fromlist=mn.split('.')[:-1])
ModuleNotFoundError: No module named 'nucleus'
ERROR:PYME.LMVis.Extras:Error loading plugin: #package_name.python_microscopy.visgui_modules.NAME_OF_FILE_WITHOUT_EXTENSION
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/Extras/__init__.py", line 46, in InitPlugins
    m = __import__(mn, fromlist=mn.split('.')[:-1])
ModuleNotFoundError: No module named '#package_name'
ERROR:PYME.LMVis.Extras:Error loading plugin: nucleus.python_microscopy.visgui_modules.distance_to_membrane
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/Extras/__init__.py", line 46, in InitPlugins
    m = __import__(mn, fromlist=mn.split('.')[:-1])
ModuleNotFoundError: No module named 'nucleus'
ERROR:PYME.LMVis.Extras:Error loading plugin: #package_name.visgui_modules.NAME_OF_FILE_WITHOUT_EXTENSION
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/Extras/__init__.py", line 46, in InitPlugins
    m = __import__(mn, fromlist=mn.split('.')[:-1])
ModuleNotFoundError: No module named '#package_name'
Creating fold panel
GenPanels
Creating datasource panel
RecipeView._layout
Input datasources:  []
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:111: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  ind = self.lFiltKeys.InsertStringItem(ind+1, key)
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:112: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 1, '%3.2f' % value[0])
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:113: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 2, '%3.2f' % value[1])
Image list size: 1
Creating layers GUI
height:  0
NB best size: wx.Size(200, 0)
RecipeView._layout
Input datasources:  []
recipe.execute()
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:111: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  ind = self.lFiltKeys.InsertStringItem(ind+1, key)
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:112: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 1, '%3.2f' % value[0])
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:113: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 2, '%3.2f' % value[1])
RecipeView._layout
Input datasources:  []
0
Ev Idle
06:38:23 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
06:38:23 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
06:38:23 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
06:38:23 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
06:38:23 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
06:38:23 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
06:38:23 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
06:38:23 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
06:38:23 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
06:38:23 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
06:38:23 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
06:38:23 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
06:38:23 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
06:38:23 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
06:38:23 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
06:38:23 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
06:38:23 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
06:38:23 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
Creating Pipeline
RecipeView._layout
06:38:24 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
06:38:24 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
Input datasources:  ['_fitResults', 'FitResults']
recipe.execute()
Executing <PYME.recipes.localisations.Pipelineify object at 0x7f29bd917f10>
DEBUG:PYME.recipes.localisations:no events found
WARNING:PYME.LMVis.pipeline:Spoofing focus from metadata: this usually implies an error in the input data (missing events) and results might vary
06:38:24 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:111: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  ind = self.lFiltKeys.InsertStringItem(ind+1, key)
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:112: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 1, '%3.2f' % value[0])
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:113: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 2, '%3.2f' % value[1])
RecipeView._layout
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /tmp/build/80754af9/wxpython_1547931003556/work/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
Input datasources:  ['_fitResults', 'FitResults']
RecipeView._layout
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /tmp/build/80754af9/wxpython_1547931003556/work/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
Input datasources:  ['_fitResults', 'FitResults']
recipe.execute()
Executing <PYME.recipes.localisations.ProcessColour object at 0x7f29b7539db0>
06:38:24 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:111: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  ind = self.lFiltKeys.InsertStringItem(ind+1, key)
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:112: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 1, '%3.2f' % value[0])
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:113: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 2, '%3.2f' % value[1])
RecipeView._layout
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /tmp/build/80754af9/wxpython_1547931003556/work/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /tmp/build/80754af9/wxpython_1547931003556/work/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
Input datasources:  ['_fitResults', 'FitResults']
recipe.execute()
06:38:24 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:111: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  ind = self.lFiltKeys.InsertStringItem(ind+1, key)
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:112: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 1, '%3.2f' % value[0])
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:113: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 2, '%3.2f' % value[1])
recipe.execute()
06:38:24 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:111: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  ind = self.lFiltKeys.InsertStringItem(ind+1, key)
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:112: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 1, '%3.2f' % value[0])
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:113: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 2, '%3.2f' % value[1])
RecipeView._layout
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /tmp/build/80754af9/wxpython_1547931003556/work/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /tmp/build/80754af9/wxpython_1547931003556/work/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:111: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  ind = self.lFiltKeys.InsertStringItem(ind+1, key)
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:112: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 1, '%3.2f' % value[0])
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:113: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 2, '%3.2f' % value[1])
Input datasources:  ['_fitResults', 'FitResults']
recipe.execute()
Executing <PYME.recipes.tablefilters.FilterTable object at 0x7f29b720ce60>
06:38:25 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:111: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  ind = self.lFiltKeys.InsertStringItem(ind+1, key)
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:112: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 1, '%3.2f' % value[0])
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:113: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 2, '%3.2f' % value[1])
RecipeView._layout
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /tmp/build/80754af9/wxpython_1547931003556/work/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /tmp/build/80754af9/wxpython_1547931003556/work/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /tmp/build/80754af9/wxpython_1547931003556/work/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:111: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  ind = self.lFiltKeys.InsertStringItem(ind+1, key)
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:112: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 1, '%3.2f' % value[0])
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:113: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 2, '%3.2f' % value[1])
Input datasources:  ['_fitResults', 'FitResults']
06:38:25 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
WARNING:PYME.LMVis.pipeline:Spoofing focus from metadata: this usually implies an error in the input data (missing events) and results might vary
Pipeline Created
RecipeView._layout
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /tmp/build/80754af9/wxpython_1547931003556/work/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /tmp/build/80754af9/wxpython_1547931003556/work/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /tmp/build/80754af9/wxpython_1547931003556/work/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:111: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  ind = self.lFiltKeys.InsertStringItem(ind+1, key)
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:112: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 1, '%3.2f' % value[0])
/home/smeagol/code/python-microscopy/PYME/LMVis/filterPane.py:113: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 2, '%3.2f' % value[1])
Input datasources:  ['_fitResults', 'FitResults']
06:38:25 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
DEBUG:PYME.LMVis.VisGUI:Creating tabs

(PYMEVis:13636): Gtk-CRITICAL **: 18:38:25.427: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed
0
DEBUG:PYME.LMVis.VisGUI:Finished creating tabs
Gui stuff done
Using recipe: None
06:38:25 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
06:38:25 PM: Debug: ScreenToClient cannot work when toplevel window is not shown
/home/smeagol/code/python-microscopy/PYME/ui/manualFoldPanel.py:37: wxPyDeprecationWarning: Using deprecated class. Use Colour instead.
  col = wx.NamedColour(col)
lw update
lw update
Traceback (most recent call last):
  File "/home/smeagol/miniconda3/lib/python3.6/site-packages/wx/core.py", line 2228, in Notify
    self.notify()
  File "/home/smeagol/miniconda3/lib/python3.6/site-packages/wx/core.py", line 3384, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/visCore.py", line 673, in _create_base_layer
    self.add_pointcloud_layer(ds_name=('output.' + c), cmap=['C', 'M', 'Y', 'R', 'G', 'B'][i%6], visible=False)
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/visCore.py", line 418, in add_pointcloud_layer
    l = PointCloudRenderLayer(self.pipeline, method=method, dsname=ds_name, **kwargs)
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/layers/pointcloud.py", line 132, in __init__
    self._set_method()
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/layers/pointcloud.py", line 149, in _set_method
    self.engine = ENGINES[self.method](self._context)
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/layers/pointcloud.py", line 20, in __init__
    self.set_shader_program(OpaquePointShaderProgram)
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/layers/base.py", line 44, in set_shader_program
    self._shader_program = ShaderProgramFactory.get_program(shader_program, self._context)
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/shader_programs/ShaderProgramFactory.py", line 46, in get_program
    new_program = class_name()
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 36, in __init__
    _shader_program = ShaderProgram(shader_path)
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/shader_programs/shader_program.py", line 59, in __init__
    raise RuntimeError('glCreateProgram failed')
RuntimeError: glCreateProgram failed
OpenGL - Version: b'4.5.0 NVIDIA 384.130'
Shader - Version: b'4.50 NVIDIA'
GL_MAX_SAMPLES: 32, GL_SAMPLES: 0
INFO:PYME.LMVis.gl_render3D_shaders:Your machine supports OpenGL antialiasing, but antialiasing disabled - enable by setting the "VisGUI-antialias_samples" PYME config setting to 4 or higher
DEBUG:PYME.LMVis.shader_programs.ShaderProgramFactory:New shader program created: <class 'PYME.LMVis.shader_programs.DefaultShaderProgram.DefaultShaderProgram'>
DEBUG:PYME.LMVis.shader_programs.ShaderProgramFactory:New shader program created: <class 'PYME.LMVis.shader_programs.DefaultShaderProgram.OpaquePointShaderProgram'>
lw update
Creating layers GUI
hl update
height:  360
NB best size: wx.Size(298, 360)
DEBUG:PYME.LMVis.visCore:Added layer, datasouce=output
/home/smeagol/code/python-microscopy/PYME/ui/histLimits.py:289: wxPyDeprecationWarning: Call to deprecated item EmptyBitmap. Use :class:`wx.Bitmap` instead
  MemBitmap = wx.EmptyBitmap(s.GetWidth(), s.GetHeight())
/home/smeagol/code/python-microscopy/PYME/ui/layerFoldPanel.py:47: wxPyDeprecationWarning: Call to deprecated item BitmapFromBuffer. Use :meth:`wx.Bitmap.FromBuffer` or :meth:`wx.Bitmap.FromBufferAndAlpha` instead.
  return wx.BitmapFromBuffer(30, 10, img)
/home/smeagol/code/python-microscopy/PYME/LMVis/layers/base.py:65: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  self.shader_program.v_matrix[3,:3] = -np.linalg.lstsq(gl_canvas.object_rotation_matrix[:3,:3], gl_canvas.view.translation)[0]
/home/smeagol/code/python-microscopy/PYME/ui/progress.py:82: wxPyDeprecationWarning: Using deprecated class. Use Cursor instead.
  self.window.SetCursor(wx.StockCursor(wx.CURSOR_WAIT))
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/genImageDialog.py", line 205, in OnZBinChange
    self.hZRange.binSize = float(self.tZThickness.GetValue())
ValueError: could not convert string to float: 
/home/smeagol/code/python-microscopy/PYME/IO/DataSources/ArrayDataSource.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  r = self.data.__getitem__(keys)
/home/smeagol/code/python-microscopy/PYME/DSView/dsviewer.py:144: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  tmp_menu.AppendMenu(-1, 'Save &Results', self.save_menu)
0
New Canvas
0
WARNING:PYME.DSView.modules:Plugin [visgui] injects into dsviewer namespace, could result in circular references
Creating fold panel
06:41:08 PM: Debug: ClientToScreen cannot work when toplevel window is not shown
OpenGL - Version: b'4.5.0 NVIDIA 384.130'
Shader - Version: b'4.50 NVIDIA'
GL_MAX_SAMPLES: 32, GL_SAMPLES: 0
INFO:PYME.LMVis.gl_render3D_shaders:Your machine supports OpenGL antialiasing, but antialiasing disabled - enable by setting the "VisGUI-antialias_samples" PYME config setting to 4 or higher
DEBUG:PYME.LMVis.shader_programs.ShaderProgramFactory:New shader program created: <class 'PYME.LMVis.shader_programs.DefaultShaderProgram.DefaultShaderProgram'>
The program 'PYMEVis' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadDrawable'.
  (Details: serial 179570 error_code 171 request_code 154 minor_code 11)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Segmentation fault (core dumped)

```

</details>

**To Reproduce**
1. PYMEImage /file
2. ~~Generate > Gaussian~~
3. ~~oh wait, that's 2D, that's not what I wanted~~
4. Generate > ~~3D Gaussian~~ (Any 3D mode)
5. set it up
6. run
7. see error

**Expected behavior**
no seg fault

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: ubuntu 16.04
 - Python version: 3.6
 - numpy version: 1.16
 - wxpython version [if a UI bug]: 4.0.4

**Comment by David-Baddeley** [comment] 2021-02-14 20:17
It's highly likely that this is a bug in one of PyOpenGL, wxPython, or GTK, which makes it rather hard to track down (and to some extent not our problem). It's rather unlikely that the shader is at fault (note the warning that these errors are reported asynchronously.

First debugging steps would be to see if this error can be reproduced in any other way (is it specific to 3D Gaussians). If (and this seems rather unlikely) the exact same sequence of steps is required to reproduce, then we could look for memory corruption / out of bounds access / reference counting errors in the 3D Gaussian code.

**Comment by David-Baddeley** [comment] 2021-02-14 22:18
Hmm, I get a similar, but different error on 18.0.4

I get a `BadMatch` error from the x server, no segfault

**Comment by David-Baddeley** [comment] 2021-02-14 22:24
A few more details:

- does not require generating a 2D image first
- not specific to Gaussian rendering (also effects 3D histogram, and 3D triangulation)
- does not effect any of the 2D modes.

These lead me to suspect that it's something about the display of 3D image stacks which is to blame (potentially GLComp).

**Comment by David-Baddeley** [comment] 2021-02-14 22:39
Narrowed down a bit further - it's the GL image viewer on 3D data

**Comment by David-Baddeley** [comment] 2021-02-15 02:31
Because the GL image viewer is currently a bit broken for stacks anyway (no way of setting the z-position & just displays the first frame), a temporary workaround would be to make lines 140 and 142 of PYME.DSView.modules.visgui only run for 2D images.

**Comment by David-Baddeley** [comment] 2021-02-25 03:33
workaround in #892, closing, but might need to revisit when we get glCanvas working for 3D data.

**Closed as completed by David-Baddeley** 2021-02-25 03:33 UTC
Labels: bug, linux
