### ISSUE TITLE
[BUG] PYMEImage crosshairs x,y and I display not updating

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#1426] opened 2023-09-18 18:23 UTC
**Describe the bug**
![image](https://github.com/python-microscopy/python-microscopy/assets/31105780/ec324935-269b-4600-9b93-f92eb7b5c67f)

**To Reproduce**
1. open PYMEImage
2. advance to a frame
3. click to move the crosshairs
4. See the intensity of 0,0,0 (x, y, z/t) instead

**Comment by David-Baddeley** [comment] 2023-09-18 19:55
Platform, versions, data file type, and any error messages on the console?

I can't reproduce on Mac, Py3.8, current repo head

**Comment by barentine** [comment] 2023-09-18 20:21
Interesting - thanks for checking, @David-Baddeley .
Windows, Py37, WX 4.0.4. Current repo head.

<details> <summary> Conda list </summary>

```
# packages in environment at C:\Users\aesb\Miniconda3\envs\pymedev:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py37_0    anaconda
anyio                     3.5.0            py37haa95532_0    anaconda
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               21.3.0             pyhd3eb1b0_0    anaconda
argon2-cffi-bindings      21.2.0           py37h2bbff1b_0    anaconda
atomicwrites              1.4.0                      py_0    anaconda
attrs                     22.1.0           py37haa95532_0    anaconda
babel                     2.11.0           py37haa95532_0    anaconda
backcall                  0.2.0              pyhd3eb1b0_0    anaconda
beautifulsoup4            4.11.1           py37haa95532_0    anaconda
bic-gmm                   23.6.21                   dev_0    <develop>
blas                      1.0                         mkl    anaconda
bleach                    4.1.0              pyhd3eb1b0_0    anaconda
blosc                     1.21.3               h6c2663c_0    anaconda
bottleneck                1.3.5            py37h080aedc_0    anaconda
brotli                    1.0.9                h2bbff1b_7    anaconda
brotli-bin                1.0.9                h2bbff1b_7    anaconda
brotlipy                  0.7.0           py37h2bbff1b_1003    anaconda
bzip2                     1.0.8                he774522_0    anaconda
ca-certificates           2023.01.10           haa95532_0    anaconda
cairo                     1.16.0               h1c23506_3    anaconda
cattrs                    23.1.0                   pypi_0    pypi
certifi                   2022.12.7        py37haa95532_0    anaconda
cffi                      1.15.1           py37h2bbff1b_3    anaconda
chardet                   4.0.0           py37haa95532_1003    anaconda
charset-normalizer        2.0.4              pyhd3eb1b0_0    anaconda
cheroot                   8.5.2            py37haa95532_1    anaconda
cherrypy                  18.6.0           py37haa95532_0    anaconda
cloudpickle               2.0.0              pyhd3eb1b0_0    anaconda
colorama                  0.4.6            py37haa95532_0    anaconda
conda                     23.1.0           py37haa95532_0    anaconda
conda-build               3.23.3           py37haa95532_0    anaconda
conda-package-handling    2.0.2            py37haa95532_0    anaconda
conda-package-streaming   0.7.0            py37haa95532_0    anaconda
cryptography              38.0.4           py37h21b164f_0    anaconda
cycler                    0.11.0             pyhd3eb1b0_0    anaconda
cython                    0.29.32          py37hd77b12b_0    anaconda
cytoolz                   0.12.0           py37h2bbff1b_0    anaconda
dask-core                 2021.10.0          pyhd3eb1b0_0    anaconda
debugpy                   1.5.1            py37hd77b12b_0    anaconda
decorator                 5.1.1              pyhd3eb1b0_0    anaconda
defusedxml                0.7.1              pyhd3eb1b0_0    anaconda
django                    2.1                      py37_0    anaconda
docutils                  0.18.1           py37haa95532_3    anaconda
double-helix              23.5.4                    dev_0    <develop>
entrypoints               0.4              py37haa95532_0    anaconda
esbonio                   0.16.1                   pypi_0    pypi
exceptiongroup            1.1.1                    pypi_0    pypi
expat                     2.4.9                h6c2663c_0    anaconda
fftw                      3.3.9                h2bbff1b_1    anaconda
filelock                  3.9.0            py37haa95532_0    anaconda
flit-core                 3.6.0              pyhd3eb1b0_0    anaconda
fontconfig                2.14.1               hc0defaf_1    anaconda
fonttools                 4.25.0             pyhd3eb1b0_0    anaconda
freetype                  2.12.1               ha860e81_0    anaconda
fsspec                    2022.11.0        py37haa95532_0    anaconda
future                    0.18.2                   py37_1    anaconda
glib                      2.69.1               h5dc1a3c_2    anaconda
glob2                     0.7                pyhd3eb1b0_0    anaconda
gst-plugins-base          1.18.5               h9e645db_0    anaconda
gstreamer                 1.18.5               hd78058f_0    anaconda
hdf5                      1.8.18           vc14h7a021fe_0  [vc14]  anaconda
icc_rt                    2022.1.0             h6049295_2    anaconda
icu                       58.2             vc14hc45fdbb_0  [vc14]  anaconda
idna                      3.4              py37haa95532_0    anaconda
ifaddr                    0.1.6                      py_0    david_baddeley
imageio                   2.19.3           py37haa95532_0    anaconda
imagesize                 1.4.1            py37haa95532_0    anaconda
importlib-metadata        4.11.3           py37haa95532_0    anaconda
importlib_metadata        4.11.3               hd3eb1b0_0    anaconda
importlib_resources       5.2.0              pyhd3eb1b0_1    anaconda
iniconfig                 1.1.1              pyhd3eb1b0_0    anaconda
intel-openmp              2021.4.0          haa95532_3556    anaconda
ipykernel                 6.15.2           py37haa95532_0    anaconda
ipympl                    0.8.7              pyhd3eb1b0_0    anaconda
ipython                   7.31.1           py37haa95532_1    anaconda
ipython_genutils          0.2.0              pyhd3eb1b0_1    anaconda
ipywidgets                7.6.5              pyhd3eb1b0_1    anaconda
jaraco.classes            3.2.1              pyhd3eb1b0_0    anaconda
jaraco.collections        3.3.0              pyhd3eb1b0_0    anaconda
jaraco.functools          3.3.0              pyhd3eb1b0_0    anaconda
jaraco.text               3.5.1            py37haa95532_2    anaconda
jedi                      0.18.1           py37haa95532_1    anaconda
jinja2                    3.1.2            py37haa95532_0    anaconda
joblib                    1.1.1            py37haa95532_0    anaconda
jpeg                      9e                   h2bbff1b_0    anaconda
json5                     0.9.6              pyhd3eb1b0_0    anaconda
jsonschema                4.16.0           py37haa95532_0    anaconda
jupyter                   1.0.0            py37haa95532_8    anaconda
jupyter_client            7.4.8            py37haa95532_0    anaconda
jupyter_console           6.4.4            py37haa95532_0    anaconda
jupyter_core              4.11.1           py37haa95532_0    anaconda
jupyter_server            1.23.4           py37haa95532_0    anaconda
jupyterlab                3.5.3            py37haa95532_0    anaconda
jupyterlab_pygments       0.1.2                      py_0    anaconda
jupyterlab_server         2.16.5           py37haa95532_0    anaconda
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    anaconda
kiwisolver                1.4.4            py37hd77b12b_0    anaconda
libarchive                3.6.2                hebabd0d_0    anaconda
libbrotlicommon           1.0.9                h2bbff1b_7    anaconda
libbrotlidec              1.0.9                h2bbff1b_7    anaconda
libbrotlienc              1.0.9                h2bbff1b_7    anaconda
libclang                  12.0.0          default_h627e005_2    anaconda
libffi                    3.4.2                hd77b12b_6    anaconda
libiconv                  1.16                 h2bbff1b_2    anaconda
liblief                   0.12.3               hd77b12b_0    anaconda
libogg                    1.3.5                h2bbff1b_1    anaconda
libpng                    1.6.37               h2a8f88b_0    anaconda
libsodium                 1.0.18               h62dcd97_0    anaconda
libtiff                   4.0.8           vc14h04e2a1e_10  [vc14]  anaconda
libvorbis                 1.3.7                he774522_0    anaconda
libwebp                   1.2.4                h2bbff1b_0    anaconda
libwebp-base              1.2.4                h2bbff1b_0    anaconda
libxml2                   2.9.14               h0ad7f3c_0    anaconda
libxslt                   1.1.35               h2bbff1b_0    anaconda
locket                    1.0.0            py37haa95532_0    anaconda
lsprotocol                2023.0.0a1               pypi_0    pypi
lxml                      4.9.1            py37h1985fb9_0    anaconda
lz4-c                     1.9.4                h2bbff1b_0    anaconda
lzo                       2.10             vc14h0a64fa6_1  [vc14]  anaconda
m2-msys2-runtime          2.5.0.17080.65c939c               3
m2-patch                  2.7.5                         2
markupsafe                2.1.1            py37h2bbff1b_0    anaconda
matplotlib                3.5.2            py37haa95532_0    anaconda
matplotlib-base           3.5.2            py37hd77b12b_0    anaconda
matplotlib-inline         0.1.6            py37haa95532_0    anaconda
menuinst                  1.4.19           py37h59b6b97_0    anaconda
mistune                   0.8.4           py37hfa6e2cd_1001    anaconda
mkl                       2021.4.0           haa95532_640    anaconda
mkl-service               2.4.0            py37h2bbff1b_0    anaconda
mkl_fft                   1.3.1            py37h277e83a_0    anaconda
mkl_random                1.2.2            py37hf11a4ad_0    anaconda
mock                      5.0.2                    pypi_0    pypi
more-itertools            8.12.0             pyhd3eb1b0_0    anaconda
mpld3                     0.5.7              pyhd3eb1b0_0    anaconda
msys2-conda-epoch         20160418                      1
munkres                   1.1.4                      py_0    anaconda
nbclassic                 0.4.8            py37haa95532_0    anaconda
nbclient                  0.5.13           py37haa95532_0    anaconda
nbconvert                 6.5.4            py37haa95532_0    anaconda
nbformat                  5.7.0            py37haa95532_0    anaconda
nep-fitting               1.9                       dev_0    <develop>
nest-asyncio              1.5.6            py37haa95532_0    anaconda
networkx                  2.6.3              pyhd3eb1b0_0    anaconda
notebook                  6.5.2            py37haa95532_0    anaconda
notebook-shim             0.2.2            py37haa95532_0    anaconda
numexpr                   2.8.4            py37h5b0cc5e_0    anaconda
numpy                     1.21.5           py37h7a0a035_3    anaconda
numpy-base                1.21.5           py37hca35cd5_3    anaconda
numpydoc                  1.5.0                    pypi_0    pypi
openssl                   1.1.1s               h2bbff1b_0    anaconda
packaging                 22.0             py37haa95532_0    anaconda
pandas                    1.3.5            py37h6214cd6_0    anaconda
pandocfilters             1.5.0              pyhd3eb1b0_0    anaconda
parso                     0.8.3              pyhd3eb1b0_0    anaconda
partd                     1.2.0              pyhd3eb1b0_1    anaconda
pcre                      8.45                 hd77b12b_0    anaconda
pickleshare               0.7.5           pyhd3eb1b0_1003    anaconda
pillow                    9.3.0            py37hdc2b20a_1    anaconda
pip                       22.3.1           py37haa95532_0    anaconda
pixman                    0.34.0           vc14h00fde18_1  [vc14]  anaconda
pkginfo                   1.8.3            py37haa95532_0    anaconda
pkgutil-resolve-name      1.3.10           py37haa95532_0    anaconda
pluggy                    1.0.0            py37haa95532_1    anaconda
ply                       3.11                     py37_0    anaconda
portend                   2.7.1              pyhd3eb1b0_0    anaconda
prometheus_client         0.14.1           py37haa95532_0    anaconda
prompt-toolkit            3.0.20             pyhd3eb1b0_0    anaconda
prompt_toolkit            3.0.20               hd3eb1b0_0    anaconda
psutil                    5.9.0            py37h2bbff1b_0    anaconda
py                        1.11.0             pyhd3eb1b0_0    anaconda
py-lief                   0.12.3           py37hd77b12b_0    anaconda
pycairo                   1.21.0           py37h501fba9_0    anaconda
pycosat                   0.6.4            py37h2bbff1b_0    anaconda
pycparser                 2.21               pyhd3eb1b0_0    anaconda
pyface                    7.1.0                    py37_1    anaconda
pyfftw                    0.11.1+26.g101c792          pypi_0    pypi
pygls                     1.0.2                    pypi_0    pypi
pygments                  2.11.2             pyhd3eb1b0_0    anaconda
pyme-depends              1.20                     py37_0    david_baddeley
pymecompress              0.3.5                    py37_0    david_baddeley
pyopengl                  3.1.1a1          py37haa95532_0    anaconda
pyopenssl                 22.0.0             pyhd3eb1b0_0    anaconda
pyparsing                 3.0.9            py37haa95532_0    anaconda
pyqt                      5.15.7           py37hd77b12b_0    anaconda
pyqt5-sip                 12.11.0          py37hd77b12b_0    anaconda
pyrsistent                0.18.0           py37h196d8e1_0    anaconda
pysocks                   1.7.1                    py37_1    anaconda
pyspellchecker            0.7.2                    pypi_0    pypi
pytables                  3.4.4            py37h0f9c03a_0    anaconda
pytest                    7.1.2            py37haa95532_0    anaconda
python                    3.7.16               h6244533_0    anaconda
python-dateutil           2.8.2              pyhd3eb1b0_0    anaconda
python-fastjsonschema     2.16.2           py37haa95532_0    anaconda
python-libarchive-c       2.9                pyhd3eb1b0_1    anaconda
python-microscopy         23.6.15.post0.dev0           dev_0    <develop>
pytz                      2022.7           py37haa95532_0    anaconda
pywavelets                1.3.0            py37h2bbff1b_0    anaconda
pywin32                   305              py37h2bbff1b_0    anaconda
pywinpty                  2.0.2            py37h5da7b33_0    anaconda
pyyaml                    5.3.1            py37he774522_0    anaconda
pyzmq                     23.2.0           py37hd77b12b_0    anaconda
qt-main                   5.15.2               he8e5bd7_7    anaconda
qt-webengine              5.15.9               hb9a9bb5_5    anaconda
qtconsole                 5.4.0            py37haa95532_0    anaconda
qtpy                      2.2.0            py37haa95532_0    anaconda
qtwebkit                  5.212                h3ad3cdb_4    anaconda
repoze.lru                0.7              py37haa95532_0    anaconda
requests                  2.28.1           py37haa95532_0    anaconda
routes                    2.5.1            py37haa95532_0    anaconda
ruamel.yaml               0.17.21          py37h2bbff1b_0    anaconda
ruamel.yaml.clib          0.2.6            py37h2bbff1b_1    anaconda
scikit-image              0.19.3           py37hd77b12b_1    anaconda
scikit-learn              1.0.2            py37hf11a4ad_1    anaconda
scipy                     1.7.3            py37h7a0a035_2    anaconda
seaborn                   0.12.2           py37haa95532_0    anaconda
send2trash                1.8.0              pyhd3eb1b0_1    anaconda
setuptools                65.6.3           py37haa95532_0    anaconda
simplejson                3.17.6           py37h2bbff1b_0    anaconda
sip                       6.6.2            py37hd77b12b_0    anaconda
six                       1.16.0             pyhd3eb1b0_1    anaconda
sniffio                   1.2.0            py37haa95532_1    anaconda
snowballstemmer           2.2.0              pyhd3eb1b0_0    anaconda
soupsieve                 2.3.2.post1      py37haa95532_0    anaconda
sphinx                    5.0.2            py37haa95532_0    anaconda
sphinx-rtd-theme          1.2.2                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0    anaconda
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0    anaconda
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0    anaconda
sphinxcontrib-jquery      4.1                      pypi_0    pypi
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0    anaconda
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0    anaconda
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0    anaconda
sqlite                    3.40.1               h2bbff1b_0    anaconda
ste-analysis              0.0.0                     dev_0    <develop>
tempora                   4.1.1              pyhd3eb1b0_0    anaconda
terminado                 0.17.1           py37haa95532_0    anaconda
threadpoolctl             2.2.0              pyh0d69192_0    anaconda
tifffile                  2021.11.2                pypi_0    pypi
tinycss2                  1.2.1            py37haa95532_0    anaconda
tk                        8.6.7            vc14hb68737d_1  [vc14]  anaconda
toml                      0.10.2             pyhd3eb1b0_0    anaconda
tomli                     2.0.1            py37haa95532_0    anaconda
toolz                     0.12.0           py37haa95532_0    anaconda
toposort                  1.5                      py37_3    david_baddeley
tornado                   6.2              py37h2bbff1b_0    anaconda
tqdm                      4.64.1           py37haa95532_0    anaconda
traitlets                 5.7.1            py37haa95532_0    anaconda
traits                    6.2.0            py37h2bbff1b_0    anaconda
traitsui                  7.1.0                      py_0    anaconda
typeguard                 3.0.2                    pypi_0    pypi
typing-extensions         4.4.0            py37haa95532_0    anaconda
typing_extensions         4.4.0            py37haa95532_0    anaconda
ujson                     5.4.0            py37hd77b12b_0    anaconda
urllib3                   1.26.14          py37haa95532_0    anaconda
vc                        14.2                 h21ff451_1    anaconda
vs2015_runtime            14.27.29016          h5e58377_2    anaconda
wcwidth                   0.2.5              pyhd3eb1b0_0    anaconda
webencodings              0.5.1                    py37_1    anaconda
websocket-client          0.58.0           py37haa95532_4    anaconda
wheel                     0.37.1             pyhd3eb1b0_0    anaconda
widgetsnbextension        3.5.2            py37haa95532_0    anaconda
win_inet_pton             1.1.0            py37haa95532_0    anaconda
wincertstore              0.2              py37haa95532_2    anaconda
winpty                    0.4.3                         4    anaconda
wxpython                  4.0.4            py37ha925a31_0    anaconda
xz                        5.2.10               h8cc25b3_1    anaconda
yaml                      0.1.7            vc14h4cb57cf_1  [vc14]  anaconda
zc.lockfile               2.0                pyhd3eb1b0_0    anaconda
zeroconf                  0.28.6                   py37_3    david_baddeley
zeromq                    4.3.4                hd77b12b_0    anaconda
zipp                      3.11.0           py37haa95532_0    anaconda
zlib                      1.2.13               h8cc25b3_0    anaconda
zstandard                 0.18.0           py37h2bbff1b_0    anaconda
zstd                      1.5.2                h19a0ad4_0    anaconda

```

</details>

I see now it does actually update the first time I click, but not thereafter, and there is a traceback:
```

ERROR:PYME.DSView.displayOptions:Error in OnChange
Traceback (most recent call last):
  File "c:\userfiles\andrew\code\python-microscopy\PYME\DSView\displayOptions.py", line 332, in OnChange
    fcn()
  File "c:\userfiles\andrew\code\python-microscopy\PYME\DSView\dsviewer.py", line 282, in update
    statusText += '    I: (%s)' % ', '.join(['%3.3f' % self.do.ds[self.do.xp, self.do.xp, self.do.zp, self.do.tp, c] for c in range(self.do.ds.shape[4])])
  File "c:\userfiles\andrew\code\python-microscopy\PYME\DSView\dsviewer.py", line 282, in <listcomp>
    statusText += '    I: (%s)' % ', '.join(['%3.3f' % self.do.ds[self.do.xp, self.do.xp, self.do.zp, self.do.tp, c] for c in range(self.do.ds.shape[4])])
  File "c:\userfiles\andrew\code\python-microscopy\PYME\IO\DataSources\BaseDataSource.py", line 348, in __getitem__
    return out.squeeze(axis=tuple(to_squeeze))
ValueError: cannot select an axis to squeeze out which has size not equal to one

```

Note that I opened an h5 file

**Comment by David-Baddeley** [comment] 2023-09-19 00:25
Confirmed with .h5 on mac ...

**Comment by David-Baddeley** [comment] 2023-09-19 00:44
And now fixed in #1427

**Closed as completed** 2023-09-19 00:45 UTC
Labels: bug

**Comment by David-Baddeley** [comment] 2023-09-19 00:50
Specific bug was a bit nasty ... would only trigger on non-square images when you clicked outside the square region and then disabled updates for subsequent clicks.

**Comment by barentine** [comment] 2023-09-19 01:12
Yikes - glad you found it. Thanks!
